services:
#    mesclics_utils.example:
#        class: MesClics\UtilsBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    
    mesclics_utils.apis_manager:
        class: MesClics\UtilsBundle\ApisManager\ApisManager
        arguments:
         - '%apis_classes%'
         - '@session'

    mesclics_utils.trello_api:
        class: MesClics\UtilsBundle\ApisManager\RestApis\TrelloApi\TrelloApi
        arguments:
            - '%trello%'
            - '@session'

    MesClics\UtilsBundle\Widget\Widget:
        abstract: true
        autowire: true

    MesClics\UtilsBundle\Widget\Handler:
        abstract: true
        autowire: true

