services:
#    mesclics_utils.example:
#        class: MesClics\UtilsBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    
    #récupère un item + celui qui le précède et celui qui le suit dans une liste de résultats
    mesclics_utils.prevcurrnext:
        class: MesClics\UtilsBundle\PrevCurrNext\MesClicsPrevCurrNext
    
    mesclics_utils.apis_manager:
        class: MesClics\UtilsBundle\ApisManager\ApisManager
        arguments:
         - '%apis_classes%'
         - '@session'

    mesclics_utils.trello_api:
        class: MesClics\UtilsBundle\ApisManager\RestApis\TrelloApi\TrelloApi
        arguments:
            - '%trello%'
            - '@session'
