services:
#    mesclics_utils.example:
#        class: MesClics\UtilsBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    
    #récupère un item + celui qui le précède et celui qui le suit dans une liste de résultats
    mesclics_utils.prevcurrnext:
        class: MesClics\UtilsBundle\PrevCurrNext\MesClicsPrevCurrNext

    #permet la pagination d'une liste de résultats
    mesclics_utils.paginator:
        class: MesClics\UtilsBundle\Paginator\MesClicsPaginator
        arguments:
            - 15 #nb d'items par page : perPage

    #ajoute une extension twig permettant l'affichage d'une liste de résultat après pagination
    mesclics_utils.twig.pagination_extension:
        class: MesClics\UtilsBundle\Twig\PaginationExtension
        arguments:
            - "@mesclics_utils.paginator"
        tags:
            - { name: twig.extension }
    
    #permet l'ajout d'attributs dans une vue twig de manière plus lisible
    mesclics_utils.html_attr_adder:
        class: MesClics\UtilsBundle\HTMLAttrAdder\HTMLAttrAdder

    #ajoute une extension twig permettant l'ajout d'attributs suivant des conditions if else if de manière plus lisible pour le code
    mesclics_utils.twig.html_attr_adder_extension:
        class: MesClics\UtilsBundle\Twig\HTMLAttrAdderExtension
        arguments:
            - "@mesclics_utils.html_attr_adder"
        tags:
            - { name: twig.extension }